### ISSUE TITLE
Nutzerverwaltung: Sperren von Nutzerkonten

### ISSUE THREAD

**Issue by ilinde** [nie-ine/nieOS#159]
Lieber Jan, 
aus den Gesprächen mit Danielle hat sich ergeben, dass wir Konten auch sperren können müssen: Wenn ein User gegen das Recht oder unsere Nutzungsbedingungen verstösst und wir das feststellen, darf er keinen Zugang mehr zum Konto haben, aber die Daten müssen aus Beweisgründen für eine bestimmte Frist vorgehalten werden. Erhebt der User innerhalb der Frist keinen Einspruch und ist aus rechtlichen Gründen kein Vorhalten der Daten mehr erforderlich, kann das Konto gelöscht werden.
LG, Iris

**Comment by janCstoffregen** [comment]
Das können wir jetzt schon!

**Comment by janCstoffregen** [comment]
Kann ich die Story schliessen?

**Comment by ilinde** [comment]
super! Ja, klar!
