### ISSUE TITLE
Nutzerbestimmungen akzeptieren

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/nieOS#161]

**Comment by janCstoffregen** [comment]
wenn man das feld nicht ankreuzt, kann man sich nicht registrieren

**Comment by janCstoffregen** [comment]
@ilinde braucht es eine extra seite bei NIE-OS, wo man die Nutzerbestimmungen einsehen kann?

**Comment by ilinde** [comment]
ja, ich denke, das wäre gut. Also es sollte so sein, dass man die Nutzungsbestimmungen und die Datenschutzerklärung einzeln verlinken kann.

**Comment by janCstoffregen** [comment]
Können sich beide Texte auf einer Seite befinden? Dann könnten sie auch einzelnd verlinkt werden,
nieos#Nutzungsbestimmungen und
nieos#Datenschutzerklärung.

ok?

**Comment by janCstoffregen** [comment]
muss man beidem einzeln zustimmen beim registrieren?

**Comment by ilinde** [comment]
Ich denke, man muss auf beides verweisen, aber ein Häkchen genügt. Ich kann aber am Mittwoch Danielle zur Sicherheit nochmal fragen.

**Comment by janCstoffregen** [comment]
ok
