### ISSUE TITLE
Usability: opening / closing apps within a view 

### ISSUE THREAD

**Issue by domsteinbach** [nie-ine/nieOS#36]
Just a tiny proposal for enhancement: 

Within a view there are several options available when we click on the icon of an app: 
- "open [app name]"
- "close this app"

My proposal is:
- to rename the menu entry "close app" to "remove app"
- to rename the menu entry "open [app name]" to "show app"

Further it could be nice to:
- fade out/grey out the icon/text of hidden/minimized apps or mark them somehow as not visible (closed eye icon or sth.)
- maybe create an additional menu entry "hide app" which effects the same like minimizing the app via the minimizing icon within the app control bar.

Substantiation:
- Closing/opening usually are two opposite effects on an object. Here they are effecting sth. completely different: "close app" is "removing" the app from the view; "open app" is showing the added app window. 
- removing is the true opposite action of adding an app to a view
- "hiding" is more precise: hide/show is exactly whats the effect of minimizing/showing the app within a view

**Comment by janCstoffregen** [comment]
everthing can be implemented here
https://github.com/nie-ine/nieOS/tree/devel/src/app/nie-OS/nie-OS

**Comment by Vijeinath** [comment]
"close app" is renamed to "remove app"
"open [app name]" is renamed to "show app"
