### ISSUE TITLE
Create popup dialog when clicking on user status

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/nieOS#39]
Klick auf "Einstellungen", dann soll sich ein mat-dialog öffnen, für die User - Settings ( ändern von username, password, ...)

mat dialog gibt es schon wird hier geöffnet:
https://github.com/nie-ine/nieOS/blob/devel/src/app/dashboard/dashboard/dashboard.component.ts#L40

und .ts ist hier geschrieben
https://github.com/nie-ine/nieOS/blob/devel/src/app/dashboard/dashboard/dashboard.component.ts#L81

und html ist hier geschrieben
https://github.com/nie-ine/nieOS/blob/devel/src/app/dashboard/dashboard/dialog-overview-example-dialog.html

für das design einfach bei bestehenden dialogs abschauen

![screen shot 2018-10-17 at 11 04 32](https://user-images.githubusercontent.com/25609132/47075242-759d3180-d1fc-11e8-8919-7882c14e7c56.png)

um es weiterzuführen, dann auch gleich die Funktionalität implementieren. wenn sehr umfangreich, dann als eigenes issue

**Comment by janCstoffregen** [comment]
für die usersettings bitte auch das pflichtenheft beachten

**Comment by Vijeinath** [comment]
Mat Dialog ist erstellt und beinhaltet die Felder (Pflichtenheft). Zur Zeit zeigt es nur Dummy Daten an und speichert noch nichts ab

**Comment by janCstoffregen** [comment]
Sieht super aus, danke!
