### ISSUE TITLE
open more frames of d3 apps of one kind

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/nieOS#43]
this works already for bar chart.

since div selector is generated dynamically
https://github.com/nie-ine/nieOS/blob/NIE-448-integrate-nodejs/src/app/nie-OS/apps/d3js/bar-chart/bar-chart.component.html

https://github.com/nie-ine/nieOS/blob/NIE-448-integrate-nodejs/src/app/nie-OS/apps/d3js/bar-chart/bar-chart.component.ts#L48

input comes from here: ( as an example )
https://github.com/nie-ine/nieOS/blob/NIE-448-integrate-nodejs/src/app/nie-OS/nie-OS/nie-OS.component.html#L523

do for every d3.js app that does not have it yet

**Comment by Padlina** [comment]
The same problem appears in the stacked bar chart.

**Comment by janCstoffregen** [comment]
fixed in NIE-MEAN
