### ISSUE TITLE
Bevor wir nieOS veröffentlichen Popup

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/nieOS#46]
Klar machen, dass es nicht produktiv, sondern in der Entwicklung ist, durch ein Popup!!!

@domsteinbach zur info

wie bei raeber
http://raeber.nie-ine.ch/init

bei jeder url, auf die man als erstes kommt

**Comment by Vijeinath** [comment]
Ist implementiert: Fehlt noch der Text in den verschiedenen Sprachen

**Comment by Vijeinath** [comment]
Ist implmentiert. Fehlt noch der Text in den verschieden Sprachen

**Comment by Vijeinath** [comment]
ist Implementiert. Fehlt noch der Text in den verschiedenen Sprachen.

**Comment by Vijeinath** [comment]
ist Implementiert. Fehlt noch der Text in den verschiedenen Sprachen.
