### ISSUE TITLE
Add navigation helper to header

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/nieOS#54]
if you're logged in --> implement button in header "go to dashboard" which should always appear ( in page and pageSet )

**Comment by janCstoffregen** [comment]
<img width="424" alt="screen shot 2018-10-22 at 16 37 51" src="https://user-images.githubusercontent.com/25609132/47298763-e12a3900-d618-11e8-85ca-7775c8b9b75b.png">

pfeil nach oben fürht zurück zum dashboard

**Comment by janCstoffregen** [comment]
neben der jeweiligen Bezeichnung ( page, pageSet ) einen Pfeil auf der linken Seite

**Comment by Vijeinath** [comment]
I added an arrow facing upwards from unicode on the left side

**Comment by janCstoffregen** [comment]
hi, danke, der Pfeil gefällt mir super, danke!, er erscheint jedoch bei der landing page /home ebenfalls, dies bitte noch beheben.

**Comment by janCstoffregen** [comment]
und einstellungen bitte nur beim Dashboard erscheinen lassen
